version: '3.8'

services:
  app:
    platform: linux/amd64
    build: .
    ports:
      - "3000:3000"  # Node.jsアプリケーションがリッスンするポート
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=mydatabase
    volumes:
      - .:/app
      - /app/node_modules
    # doocker compose upをしたら実行されるコマンド
    command: sh -c "npm install && npm start" #nodemanの追加&nodemoduleをvolumeにマウントして毎回実行させないようにさせるあとで。

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"  
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # tableの内容のiniなど(rootにあるけど、dockerをbuildするときにこのdirに書かすようにしている。)


volumes:
  db_data: