version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"  # Node.jsアプリケーションがリッスンするポート
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=mydatabase
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm start"

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"  # 修正: MySQLのデフォルトポートは3306です
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:


